package javaapplication20;


//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONTRASENYA = 12;
  public static final int COMA = 11;
  public static final int DEPARTAMENTOS = 5;
  public static final int TRABAJADORES = 6;
  public static final int PAR_SAL = 8;
  public static final int EOF = 0;
  public static final int PAR_ENT = 7;
  public static final int CORREO = 13;
  public static final int PYC = 9;
  public static final int PALABRA = 3;
  public static final int SALTO = 10;
  public static final int CARGOS = 4;
  public static final int error = 1;
  public static final int TELEFONO = 14;
  public static final int CIFRA = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CIFRA",
  "PALABRA",
  "CARGOS",
  "DEPARTAMENTOS",
  "TRABAJADORES",
  "PAR_ENT",
  "PAR_SAL",
  "PYC",
  "SALTO",
  "COMA",
  "CONTRASENYA",
  "CORREO",
  "TELEFONO"
  };
}

